#!/bin/bash
if [ $# -ne 2 ]
  then
    echo "Error in number of arguments"
    exit 1
fi
# vars
DB_NAME="straeto"
SHP_FILE=$1
SHP_FILE_SPHEROID=4326
OUTPUT_PATH=$2

# dropping database if exists
dropdb $DB_NAME

# creating database
createdb $DB_NAME
psql $DB_NAME -c 'CREATE EXTENSION postgis'

# insterting data into database from shapefile
shp2pgsql -s $SHP_FILE_SPHEROID $SHP_FILE roads | psql $DB_NAME

# extracting road shapefiles from database
OUTPUT_PATH="$(realpath $OUTPUT_PATH)"
(mkdir -p $OUTPUT_PATH && cd $_ && pgsql2shp -f extracted_roads $DB_NAME "SELECT osm_id, geom FROM roads WHERE fclass IN \
('motorway', 'trunk', 'primary', 'secondary', 'tertiary', 'unclassified', 'residential', 'service', 'motorway_link', 'trunk_link', 'primary_link', 'secondary_link', 'tertiary_link') AND maxspeed > 0")
(mkdir -p $OUTPUT_PATH && cd $_ && pgsql2shp -f no_extracted_roads $DB_NAME "SELECT osm_id, geom FROM roads WHERE fclass IN \
('motorway', 'trunk', 'primary', 'secondary', 'tertiary', 'unclassified', 'residential', 'service', 'motorway_link', 'trunk_link', 'primary_link', 'secondary_link', 'tertiary_link') AND maxspeed = 0")